OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/SUBGRUPOS.csv'
INTO TABLE SUBGRUPOS
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
PRESERVE BLANKS
(
  ID                                  INTEGER EXTERNAL NULLIF ID=BLANKS,
  ID_PRIMARIO                         INTEGER EXTERNAL NULLIF ID_PRIMARIO=BLANKS,
  ID_SECUNDARIO                       INTEGER EXTERNAL NULLIF ID_SECUNDARIO=BLANKS
)
