OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/ENTRADAS_PAYLOAD_STAGING.csv'
INTO TABLE ENTRADAS_PAYLOAD_STAGING
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
PRESERVE BLANKS
(
  ID                                  INTEGER EXTERNAL NULLIF ID=BLANKS,
  RECEBIDO_EM                         TIMESTAMP "YYYY-MM-DD HH24:MI:SS.FF" NULLIF RECEBIDO_EM=BLANKS,
  PAYLOAD                             CHAR(1000000) NULLIF PAYLOAD=BLANKS,
  EXECUTION_ID                        CHAR(36) NULLIF EXECUTION_ID=BLANKS,
  EXECUTION_TYPE                      CHAR(50) NULLIF EXECUTION_TYPE=BLANKS
)
