OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/OFERTAS_IGREJAS.csv'
INTO TABLE OFERTAS_IGREJAS
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
PRESERVE BLANKS
(
  OFERTA_ID                           INTEGER EXTERNAL NULLIF OFERTA_ID=BLANKS,
  COD_IGREJA                          INTEGER EXTERNAL NULLIF COD_IGREJA=BLANKS
)
