OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/PERMISSIONS.csv'
INTO TABLE PERMISSIONS
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
PRESERVE BLANKS
(
  ID                                  INTEGER EXTERNAL NULLIF ID=BLANKS,
  NAME                                CHAR(100) NULLIF NAME=BLANKS,
  DESCRIPTION                         CHAR(255) NULLIF DESCRIPTION=BLANKS
)
