OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/ROLE_PERMISSIONS.csv'
INTO TABLE ROLE_PERMISSIONS
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  ROLE_ID                             INTEGER EXTERNAL NULLIF ROLE_ID=BLANKS,
  PERMISSION_ID                       INTEGER EXTERNAL NULLIF PERMISSION_ID=BLANKS
)
