OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/SUBGRUPO_PROJETO.csv'
INTO TABLE SUBGRUPO_PROJETO
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
PRESERVE BLANKS
(
  PROJETO_ID                          INTEGER EXTERNAL NULLIF PROJETO_ID=BLANKS,
  SUBGRUPO_ID                         INTEGER EXTERNAL NULLIF SUBGRUPO_ID=BLANKS
)
