OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/USER_IGREJAS.csv'
INTO TABLE USER_IGREJAS
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(
  USER_ID                             INTEGER EXTERNAL NULLIF USER_ID=BLANKS,
  COD_IGREJA                          INTEGER EXTERNAL NULLIF COD_IGREJA=BLANKS
)
