OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/USER_ROLES.csv'
INTO TABLE USER_ROLES
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
PRESERVE BLANKS
(
  USER_ID                             INTEGER EXTERNAL NULLIF USER_ID=BLANKS,
  ROLE_ID                             INTEGER EXTERNAL NULLIF ROLE_ID=BLANKS
)
