OPTIONS (DIRECT=FALSE, ROWS=50000, ERRORS=100000)
LOAD DATA
CHARACTERSET AL32UTF8
INFILE './csv/USER_PROJETOS.csv'
INTO TABLE USER_PROJETOS
APPEND
FIELDS TERMINATED BY X'1F' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
PRESERVE BLANKS
(
  USER_ID                             INTEGER EXTERNAL NULLIF USER_ID=BLANKS,
  PROJETO_ID                          INTEGER EXTERNAL NULLIF PROJETO_ID=BLANKS
)
