-- 02_primary_unique_constraints.sql - PK e UK

ALTER TABLE ENTRADAS ADD CONSTRAINT PK_ENTRADAS PRIMARY KEY (ID);
ALTER TABLE GRUPOS ADD CONSTRAINT PK_GRUPOS PRIMARY KEY (ID);
ALTER TABLE IGREJAS ADD CONSTRAINT PK_IGREJAS PRIMARY KEY (ID);
ALTER TABLE IGREJAS ADD CONSTRAINT COD_IGREJA UNIQUE (COD_IGREJA);
ALTER TABLE IGREJAS ADD CONSTRAINT SQLITE_AUTOINDEX_IGREJAS_1 UNIQUE (COD_IGREJA);
ALTER TABLE IGREJAS ADD CONSTRAINT SQLITE_AUTOINDEX_IGREJAS_1_1 UNIQUE (COD_IGREJA);
ALTER TABLE IGREJAS ADD CONSTRAINT SQLITE_AUTOINDEX_IGREJAS_1_2 UNIQUE (COD_IGREJA);
ALTER TABLE IGREJAS ADD CONSTRAINT SQLITE_AUTOINDEX_IGREJAS_1_3 UNIQUE (COD_IGREJA);
ALTER TABLE IMAGES ADD CONSTRAINT PK_IMAGES PRIMARY KEY (ID);
ALTER TABLE LOCALIDADES ADD CONSTRAINT PK_LOCALIDADES PRIMARY KEY (ID);
ALTER TABLE OFERTAS ADD CONSTRAINT PK_OFERTAS PRIMARY KEY (ID);
ALTER TABLE PROJETO ADD CONSTRAINT PK_PROJETO PRIMARY KEY (ID);
ALTER TABLE SAIDAS ADD CONSTRAINT PK_SAIDAS PRIMARY KEY (ID);
ALTER TABLE SALDOS ADD CONSTRAINT PK_SALDOS PRIMARY KEY (ID);
ALTER TABLE SUBGRUPOS ADD CONSTRAINT PK_SUBGRUPOS PRIMARY KEY (ID);
ALTER TABLE TREE ADD CONSTRAINT PK_TREE PRIMARY KEY (ID);
ALTER TABLE USERS ADD CONSTRAINT PK_USERS PRIMARY KEY (ID);
ALTER TABLE PC_EXPENSE_INGEST_STATE ADD CONSTRAINT PK_PC_EXPENSE_INGEST_STATE PRIMARY KEY (ID);
ALTER TABLE PC_EXPENSE_INGEST_STATE ADD CONSTRAINT UQ_PC_EXPENSE_INGEST_STATE UNIQUE (DAY_DATE, SOURCE);
