-- 04_indexes.sql - índices secundários

CREATE INDEX IX_ENTRADAS_ID ON ENTRADAS (ID);
CREATE INDEX IX_ENTRADAS_ID_1 ON ENTRADAS (ID);
CREATE INDEX IX_GRUPOS_ID ON GRUPOS (ID);
CREATE INDEX IX_GRUPOS_ID_1 ON GRUPOS (ID);
CREATE INDEX IX_IGREJAS_ID ON IGREJAS (ID);
CREATE INDEX IX_IGREJAS_ID_1 ON IGREJAS (ID);
CREATE INDEX IX_IGREJAS_ID_2 ON IGREJAS (ID);
CREATE INDEX IX_IGREJAS_ID_3 ON IGREJAS (ID);
CREATE INDEX IX_IMAGES_ID ON IMAGES (ID);
CREATE INDEX IX_IMAGES_ID_1 ON IMAGES (ID);
CREATE INDEX IX_IMAGES_ID_2 ON IMAGES (ID);
CREATE INDEX IX_IMAGES_ID_3 ON IMAGES (ID);
CREATE INDEX IX_LOCALIDADES_ID ON LOCALIDADES (ID);
CREATE INDEX IX_LOCALIDADES_ID_1 ON LOCALIDADES (ID);
CREATE INDEX IX_OFERTAS_ID ON OFERTAS (ID);
CREATE INDEX IX_OFERTAS_ID_1 ON OFERTAS (ID);
CREATE INDEX IX_PROJETO_ID ON PROJETO (ID);
CREATE INDEX IX_PROJETO_ID_1 ON PROJETO (ID);
CREATE INDEX IX_SAIDAS_ID ON SAIDAS (ID);
CREATE INDEX IX_SALDOS_ID ON SALDOS (ID);
CREATE INDEX IX_SALDOS_ID_1 ON SALDOS (ID);
CREATE INDEX IX_SUBGRUPOS_ID ON SUBGRUPOS (ID);
CREATE INDEX IX_SUBGRUPOS_ID_1 ON SUBGRUPOS (ID);
CREATE INDEX IX_PC_EXPENSE_INGEST_STATE_ID ON PC_EXPENSE_INGEST_STATE (ID);
