-- 03_foreign_keys.sql - FKs
-- Recomenda-se executar depois da carga e validação dos dados.

ALTER TABLE ACTIVITYLOG ADD CONSTRAINT ACTIVITYLOG_IBFK_1 FOREIGN KEY (ACTOR_USER_ID) REFERENCES USERS (ID) ON DELETE SET NULL;
ALTER TABLE ENTRADA ADD CONSTRAINT ENTRADA_IBFK_1 FOREIGN KEY (COD_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE GRUPO ADD CONSTRAINT GRUPO_IBFK_1 FOREIGN KEY (OFERTA_ID) REFERENCES OFERTAS (ID);
ALTER TABLE GRUPO ADD CONSTRAINT GRUPO_IBFK_2 FOREIGN KEY (COD_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE IMAGES ADD CONSTRAINT IMAGES_IBFK_1 FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (PROJETO_ID);
ALTER TABLE IMAGES ADD CONSTRAINT IMAGES_IBFK_2 FOREIGN KEY (COD_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE IMAGES ADD CONSTRAINT IMAGES_IBFK_3 FOREIGN KEY (OFERTA_ID) REFERENCES OFERTAS (ID);
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_IBFK_1 FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID);
ALTER TABLE SAIDA ADD CONSTRAINT SAIDA_IBFK_1 FOREIGN KEY (CONTA_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE SAIDA ADD CONSTRAINT SAIDA_IBFK_2 FOREIGN KEY (OFERTA_ID) REFERENCES OFERTAS (ID);
ALTER TABLE SALDO ADD CONSTRAINT SALDO_IBFK_1 FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID);
ALTER TABLE SALDO ADD CONSTRAINT SALDO_IBFK_2 FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO (PROJETO_ID);
ALTER TABLE SALDO ADD CONSTRAINT SALDO_IBFK_3 FOREIGN KEY (ID_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE SALDO ADD CONSTRAINT SALDO_IBFK_4 FOREIGN KEY (ID_ENTRADA) REFERENCES ENTRADA (ID);
ALTER TABLE SALDO ADD CONSTRAINT SALDO_IBFK_5 FOREIGN KEY (ID_SAIDA) REFERENCES SAIDA (ID);
ALTER TABLE SALDO ADD CONSTRAINT SALDO_IBFK_6 FOREIGN KEY (COD_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE SALDO ADD CONSTRAINT SALDO_IBFK_7 FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (PROJETO_ID);
ALTER TABLE SALDOCOUNTER ADD CONSTRAINT SALDOCOUNTER_IBFK_1 FOREIGN KEY (ID_GRUPO) REFERENCES GRUPO (ID);
ALTER TABLE SALDOCOUNTER ADD CONSTRAINT SALDOCOUNTER_IBFK_2 FOREIGN KEY (ID_PROJETO) REFERENCES PROJETO (PROJETO_ID);
ALTER TABLE SALDOCOUNTER ADD CONSTRAINT SALDOCOUNTER_IBFK_3 FOREIGN KEY (ID_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE SALDOCOUNTER ADD CONSTRAINT SALDOCOUNTER_IBFK_4 FOREIGN KEY (COD_IGREJA) REFERENCES IGREJAS (COD_IGREJA);
ALTER TABLE SALDOCOUNTER ADD CONSTRAINT SALDOCOUNTER_IBFK_5 FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (PROJETO_ID);
ALTER TABLE OFERTAS_IGREJAS ADD CONSTRAINT OFERTAS_IGREJAS_IBFK_1 FOREIGN KEY (OFERTA_ID) REFERENCES OFERTAS (ID) ON DELETE CASCADE;
ALTER TABLE OFERTAS_IGREJAS ADD CONSTRAINT OFERTAS_IGREJAS_IBFK_2 FOREIGN KEY (COD_IGREJA) REFERENCES IGREJAS (COD_IGREJA) ON DELETE CASCADE;
ALTER TABLE OFERTAS_IGREJAS_HISTORICO ADD CONSTRAINT OFERTAS_IGREJAS_HISTORICO_IBFK FOREIGN KEY (OFERTA_ID) REFERENCES OFERTAS (ID) ON DELETE CASCADE ENABLE NOVALIDATE;
ALTER TABLE ROLE_PERMISSIONS ADD CONSTRAINT ROLE_PERMISSIONS_IBFK_1 FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE;
ALTER TABLE ROLE_PERMISSIONS ADD CONSTRAINT ROLE_PERMISSIONS_IBFK_2 FOREIGN KEY (PERMISSION_ID) REFERENCES PERMISSIONS (ID) ON DELETE CASCADE;
ALTER TABLE SUBGRUPO_PROJETO ADD CONSTRAINT SUBGRUPO_PROJETO_IBFK_1 FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (PROJETO_ID) ON DELETE CASCADE;
ALTER TABLE SUBGRUPO_PROJETO ADD CONSTRAINT SUBGRUPO_PROJETO_IBFK_2 FOREIGN KEY (SUBGRUPO_ID) REFERENCES PROJETO (PROJETO_ID) ON DELETE CASCADE;
ALTER TABLE USER_IGREJAS ADD CONSTRAINT USER_IGREJAS_IBFK_1 FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE USER_IGREJAS ADD CONSTRAINT USER_IGREJAS_IBFK_2 FOREIGN KEY (COD_IGREJA) REFERENCES IGREJAS (COD_IGREJA) ON DELETE CASCADE;
ALTER TABLE USER_PROJETOS ADD CONSTRAINT USER_PROJETOS_IBFK_1 FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE USER_PROJETOS ADD CONSTRAINT USER_PROJETOS_IBFK_2 FOREIGN KEY (PROJETO_ID) REFERENCES PROJETO (PROJETO_ID) ON DELETE CASCADE;
ALTER TABLE USER_ROLES ADD CONSTRAINT USER_ROLES_IBFK_1 FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE;
ALTER TABLE USER_ROLES ADD CONSTRAINT USER_ROLES_IBFK_2 FOREIGN KEY (ROLE_ID) REFERENCES ROLES (ID) ON DELETE CASCADE;
